### ISSUE TITLE
Change name on basket/portfolio

### ISSUE THREAD

**Issue by jonarnes** [cryptokid-app/feedback#16]
Trying to change name by tapping the title and removing letter by backspace works until the last (first) letter. First letter in the original name can’t be removed

**Comment by asbjornenge** [comment]
@jonarnes Hva synes du om måten å endre navnet på? Er det ikke litt rart å ha redigerbart felt i headeren der? Vurderer å flytte ned til en `Name: <input>` felt over coinsa...

**Comment by asbjornenge** [comment]
Done v1.0.6
